export { default as Home } from './Home'
export { default as About } from './About'
export { default as Skills } from './Skills'
export { default as Experiences } from './Experiences'
export { default as Projects } from './Projects'
export { default as Contact } from './Contact'